create table authors(
                        id bigserial generated by default as IDENTITY,
                        name varchar(255),
                        surname varchar(255),
                        primary key (id)
);
create table genres(
                       id bigserial generated by default as IDENTITY,
                       name varchar(255),
                       primary key (id)
);
create table books(
                      id bigserial generated by default as IDENTITY,
                      title varchar(255),
                      author_id bigint references authors(id) on delete cascade,
                      genre_id bigint references genres(id) on delete cascade,
                      primary key (id)
);
create table comments(
                      id bigserial generated by default as IDENTITY,
                      book_id bigint references books(id) on delete cascade,
                      text varchar(255),
                      primary key (id)
);